[2025-09-17T22:53:20.703+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:20.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:53:20.709+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:53:20.708+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:22.362+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:53:22.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:53:22.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:22.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 1.702 seconds
[2025-09-17T22:53:52.837+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:52.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:53:52.846+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:53:52.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:53.308+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:53:53.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:53:53.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:53:53.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.527 seconds
[2025-09-17T22:54:23.537+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:23.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:54:23.543+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:54:23.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:23.972+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:54:23.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:54:23.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:24.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.497 seconds
[2025-09-17T22:54:54.212+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:54.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:54:54.217+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:54:54.217+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:54.667+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:54:54.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:54:54.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:54:54.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.508 seconds
[2025-09-17T22:55:25.322+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:25.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:55:25.335+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:55:25.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:26.040+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:55:26.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:55:26.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:26.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.792 seconds
[2025-09-17T22:55:56.701+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:56.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:55:56.715+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:55:56.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:57.332+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:55:57.325+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:55:57.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:55:57.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.701 seconds
[2025-09-17T22:56:28.063+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:28.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:56:28.069+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:56:28.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:28.508+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:56:28.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:56:28.511+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:28.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.499 seconds
[2025-09-17T22:56:59.017+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:59.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:56:59.022+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:56:59.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:59.528+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:56:59.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:56:59.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:56:59.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.683 seconds
[2025-09-17T22:57:29.878+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:57:29.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:57:29.892+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:57:29.890+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:57:30.391+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:57:30.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:57:30.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:57:30.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.582 seconds
[2025-09-17T22:58:01.004+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:01.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:58:01.007+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:58:01.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:01.438+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:58:01.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:58:01.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:01.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.498 seconds
[2025-09-17T22:58:32.215+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:32.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:58:32.220+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:58:32.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:32.594+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:58:32.587+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:58:32.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:58:32.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.427 seconds
[2025-09-17T22:59:02.877+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:02.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:59:02.884+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:59:02.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:03.423+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:59:03.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:59:03.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:03.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.611 seconds
[2025-09-17T22:59:34.160+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:34.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T22:59:34.165+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:59:34.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:34.566+0000] {logging_mixin.py:188} INFO - [2025-09-17T22:59:34.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T22:59:34.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T22:59:34.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.449 seconds
[2025-09-17T23:00:04.789+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:04.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:00:04.794+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:00:04.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:05.266+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:00:05.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:00:05.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:05.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.536 seconds
[2025-09-17T23:00:35.981+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:35.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:00:35.984+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:00:35.983+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:36.504+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:00:36.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:00:36.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:00:36.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.575 seconds
[2025-09-17T23:01:06.811+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:06.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:01:06.817+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:01:06.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:07.280+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:01:07.270+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:01:07.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:07.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.541 seconds
[2025-09-17T23:01:37.979+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:37.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:01:37.982+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:01:37.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:38.400+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:01:38.393+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:01:38.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:01:38.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.469 seconds
[2025-09-17T23:02:08.551+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:08.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:02:08.553+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:08.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:09.003+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:08.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:02:09.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:09.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.502 seconds
[2025-09-17T23:02:39.298+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:39.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:02:39.305+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:39.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:39.767+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:39.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 7, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:02:39.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:39.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.528 seconds
[2025-09-17T23:02:56.553+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:56.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:02:56.559+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:56.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:57.039+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:02:57.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:02:57.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:02:57.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.542 seconds
[2025-09-17T23:03:27.826+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:27.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:03:27.829+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:03:27.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:28.253+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:03:28.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:03:28.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:28.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.485 seconds
[2025-09-17T23:03:58.933+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:58.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:03:58.936+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:03:58.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:59.411+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:03:59.403+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:03:59.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:03:59.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.529 seconds
[2025-09-17T23:04:30.382+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:04:30.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:04:30.385+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:04:30.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:04:30.850+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:04:30.840+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:04:30.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:04:30.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.527 seconds
[2025-09-17T23:05:01.095+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:01.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:05:01.100+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:01.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:01.528+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:01.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:05:01.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:01.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.479 seconds
[2025-09-17T23:05:31.755+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:31.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:05:31.760+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:31.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:32.397+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:32.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:05:32.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:32.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.706 seconds
[2025-09-17T23:05:34.785+0000] {processor.py:161} INFO - Started process (PID=157) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:34.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:05:34.787+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:34.787+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:35.246+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:05:35.230+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:05:35.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:05:35.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.554 seconds
[2025-09-17T23:06:05.852+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:05.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:06:05.856+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:06:05.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:06.341+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:06:06.331+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:06:06.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:06.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.548 seconds
[2025-09-17T23:06:36.477+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:36.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:06:36.480+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:06:36.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:36.959+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:06:36.951+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:06:36.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:06:37.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.541 seconds
[2025-09-17T23:07:07.288+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:07.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:07:07.293+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:07:07.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:07.775+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:07:07.766+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:07:07.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:07.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.539 seconds
[2025-09-17T23:07:38.344+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:38.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:07:38.348+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:07:38.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:38.788+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:07:38.780+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:07:38.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:07:38.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.498 seconds
[2025-09-17T23:08:08.984+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:08.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:08:08.986+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:08:08.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:09.455+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:08:09.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:08:09.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:09.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.535 seconds
[2025-09-17T23:08:40.097+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:40.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:08:40.100+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:08:40.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:40.548+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:08:40.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:08:40.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:08:40.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.502 seconds
[2025-09-17T23:09:10.671+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:10.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:09:10.674+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:10.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:11.091+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:11.079+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 8, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:09:11.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:11.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.490 seconds
[2025-09-17T23:09:16.296+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:16.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:09:16.302+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:16.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:16.881+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:16.870+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:09:16.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:16.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.666 seconds
[2025-09-17T23:09:47.563+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:47.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:09:47.566+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:47.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:47.988+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:47.979+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:09:47.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:48.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.501 seconds
[2025-09-17T23:09:55.746+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:55.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:09:55.750+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:55.749+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:56.260+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:09:56.251+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:09:56.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:09:56.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.566 seconds
[2025-09-17T23:10:26.981+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:26.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:10:26.990+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:10:26.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:27.460+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:10:27.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:10:27.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:27.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.554 seconds
[2025-09-17T23:10:58.207+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:58.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:10:58.211+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:10:58.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:58.647+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:10:58.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:10:58.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:10:58.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.486 seconds
[2025-09-17T23:11:28.877+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:11:28.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:11:28.882+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:11:28.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:11:29.325+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:11:29.314+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:11:29.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:11:29.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.514 seconds
[2025-09-17T23:12:00.167+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:00.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:12:00.170+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:12:00.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:00.646+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:12:00.637+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:12:00.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:00.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.533 seconds
[2025-09-17T23:12:30.929+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:30.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:12:30.933+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:12:30.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:31.359+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:12:31.351+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:12:31.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:12:31.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.477 seconds
[2025-09-17T23:13:02.073+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:02.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:13:02.077+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:13:02.076+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:02.457+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:13:02.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:13:02.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:02.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.457 seconds
[2025-09-17T23:13:32.910+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:32.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:13:32.915+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:13:32.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:33.363+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:13:33.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:13:33.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:13:33.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.507 seconds
[2025-09-17T23:14:04.141+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:04.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:14:04.146+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:14:04.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:04.534+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:14:04.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:14:04.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:04.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.444 seconds
[2025-09-17T23:14:34.785+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:34.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:14:34.788+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:14:34.788+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:35.168+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:14:35.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:14:35.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:14:35.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.444 seconds
[2025-09-17T23:15:05.581+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:05.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:15:05.586+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:15:05.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:05.982+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:15:05.973+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:15:05.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:06.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.466 seconds
[2025-09-17T23:15:36.719+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:36.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:15:36.722+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:15:36.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:37.216+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:15:37.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:15:37.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:15:37.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.559 seconds
[2025-09-17T23:16:08.033+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:08.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:16:08.044+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:16:08.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:08.547+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:16:08.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:16:08.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:08.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.594 seconds
[2025-09-17T23:16:39.164+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:39.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:16:39.168+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:16:39.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:39.612+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:16:39.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:16:39.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:16:39.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.507 seconds
[2025-09-17T23:17:09.807+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:09.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:17:09.814+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:17:09.813+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:10.311+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:17:10.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:17:10.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:10.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.573 seconds
[2025-09-17T23:17:41.040+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:41.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:17:41.045+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:17:41.044+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:41.461+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:17:41.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:17:41.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:17:41.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.483 seconds
[2025-09-17T23:18:11.806+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:11.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:18:11.809+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:18:11.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:12.202+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:18:12.191+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:18:12.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:12.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.462 seconds
[2025-09-17T23:18:42.478+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:42.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:18:42.481+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:18:42.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:42.914+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:18:42.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:18:42.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:18:42.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.514 seconds
[2025-09-17T23:19:13.729+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:13.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:19:13.733+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:19:13.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:14.127+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:19:14.119+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:19:14.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:14.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.457 seconds
[2025-09-17T23:19:44.894+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:44.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:19:44.899+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:19:44.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:45.302+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:19:45.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:19:45.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:19:45.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.455 seconds
[2025-09-17T23:20:15.647+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:15.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:20:15.652+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:20:15.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:16.076+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:20:16.068+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:20:16.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:16.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.493 seconds
[2025-09-17T23:20:46.323+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:46.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:20:46.328+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:20:46.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:46.795+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:20:46.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:20:46.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:20:46.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.551 seconds
[2025-09-17T23:21:17.618+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:17.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:21:17.627+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:21:17.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:18.075+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:21:18.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:21:18.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:18.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.521 seconds
[2025-09-17T23:21:48.741+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:48.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:21:48.749+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:21:48.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:49.241+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:21:49.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:21:49.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:21:49.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.576 seconds
[2025-09-17T23:22:19.963+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:19.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:22:19.967+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:22:19.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:20.384+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:22:20.375+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:22:20.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:20.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.463 seconds
[2025-09-17T23:22:50.650+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:50.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:22:50.653+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:22:50.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:51.041+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:22:51.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:22:51.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:22:51.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.442 seconds
[2025-09-17T23:23:21.301+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:21.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:23:21.305+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:23:21.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:21.694+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:23:21.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:23:21.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:21.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.453 seconds
[2025-09-17T23:23:51.987+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:51.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:23:51.989+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:23:51.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:52.418+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:23:52.409+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:23:52.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:23:52.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.500 seconds
[2025-09-17T23:24:23.137+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:23.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:24:23.141+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:24:23.140+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:23.572+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:24:23.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:24:23.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:23.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.504 seconds
[2025-09-17T23:24:53.961+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:53.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:24:53.966+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:24:53.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:54.388+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:24:54.376+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:24:54.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:24:54.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.498 seconds
[2025-09-17T23:25:25.193+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:25.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:25:25.196+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:25:25.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:25.599+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:25:25.591+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:25:25.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:25.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.464 seconds
[2025-09-17T23:25:55.940+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:55.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:25:55.944+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:25:55.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:56.327+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:25:56.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:25:56.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:25:56.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.444 seconds
[2025-09-17T23:26:26.691+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:26.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:26:26.694+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:26:26.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:27.091+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:26:27.081+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:26:27.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:27.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.464 seconds
[2025-09-17T23:26:57.393+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:57.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:26:57.398+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:26:57.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:57.911+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:26:57.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:26:57.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:26:57.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.574 seconds
[2025-09-17T23:27:28.560+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:28.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:27:28.563+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:27:28.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:29.050+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:27:29.042+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:27:29.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:29.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.539 seconds
[2025-09-17T23:27:59.275+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:59.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:27:59.278+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:27:59.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:59.736+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:27:59.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:27:59.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:27:59.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.520 seconds
[2025-09-17T23:28:30.174+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:28:30.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:28:30.177+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:28:30.177+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:28:30.587+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:28:30.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:28:30.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:28:30.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.461 seconds
[2025-09-17T23:29:01.197+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:01.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:29:01.200+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:29:01.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:01.610+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:29:01.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:29:01.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:01.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.463 seconds
[2025-09-17T23:29:31.851+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:31.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:29:31.856+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:29:31.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:32.285+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:29:32.278+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:29:32.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:29:32.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.494 seconds
[2025-09-17T23:30:02.846+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:02.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:30:02.849+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:30:02.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:03.269+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:30:03.262+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:30:03.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:03.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.465 seconds
[2025-09-17T23:30:33.421+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:33.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:30:33.424+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:30:33.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:33.825+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:30:33.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:30:33.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:30:33.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.453 seconds
[2025-09-17T23:31:04.066+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:04.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:31:04.071+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:04.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:04.549+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:04.533+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:31:04.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:04.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.566 seconds
[2025-09-17T23:31:19.933+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:19.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:31:19.939+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:19.938+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:20.439+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:20.431+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'Lake'
[2025-09-17T23:31:20.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:20.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.558 seconds
[2025-09-17T23:31:42.674+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:42.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:31:42.677+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:42.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:43.196+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:31:43.188+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:31:43.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:31:43.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.564 seconds
[2025-09-17T23:32:13.409+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:13.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:32:13.414+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:32:13.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:13.847+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:32:13.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:32:13.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:13.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.509 seconds
[2025-09-17T23:32:44.431+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:44.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:32:44.436+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:32:44.435+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:44.946+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:32:44.937+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:32:44.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:32:45.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.589 seconds
[2025-09-17T23:33:15.713+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:15.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:33:15.719+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:33:15.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:16.178+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:33:16.170+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:33:16.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:16.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.525 seconds
[2025-09-17T23:33:46.853+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:46.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:33:46.857+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:33:46.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:47.268+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:33:47.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:33:47.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:33:47.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.483 seconds
[2025-09-17T23:34:17.586+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:17.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:34:17.589+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:34:17.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:18.121+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:34:18.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:34:18.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:18.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.609 seconds
[2025-09-17T23:34:49.202+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:49.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:34:49.207+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:34:49.206+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:49.682+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:34:49.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:34:49.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:34:49.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.527 seconds
[2025-09-17T23:35:20.391+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:35:20.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:35:20.397+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:35:20.396+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:35:20.844+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:35:20.834+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
ModuleNotFoundError: No module named 'src'
[2025-09-17T23:35:20.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:35:20.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.513 seconds
[2025-09-17T23:36:04.777+0000] {processor.py:161} INFO - Started process (PID=24) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:04.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:36:04.783+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:36:04.782+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:06.641+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:36:06.626+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:36:06.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:06.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 1.918 seconds
[2025-09-17T23:36:37.008+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:37.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:36:37.016+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:36:37.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:37.576+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:36:37.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:36:37.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:36:37.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.629 seconds
[2025-09-17T23:37:07.768+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:07.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:37:07.774+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:37:07.774+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:08.306+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:37:08.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:37:08.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:08.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.592 seconds
[2025-09-17T23:37:38.913+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:38.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:37:38.920+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:37:38.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:39.471+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:37:39.455+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:37:39.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:37:39.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.617 seconds
[2025-09-17T23:38:09.644+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:09.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:38:09.651+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:38:09.651+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:10.201+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:38:10.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:38:10.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:10.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.658 seconds
[2025-09-17T23:38:40.895+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:40.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:38:40.904+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:38:40.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:41.449+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:38:41.429+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:38:41.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:38:41.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.621 seconds
[2025-09-17T23:39:12.157+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:12.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:39:12.171+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:39:12.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:12.719+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:39:12.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:39:12.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:12.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.651 seconds
[2025-09-17T23:39:43.323+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:43.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:39:43.331+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:39:43.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:43.865+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:39:43.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:39:43.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:39:43.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.605 seconds
[2025-09-17T23:40:14.540+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:14.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:40:14.548+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:40:14.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:15.164+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:40:15.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:40:15.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:15.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.703 seconds
[2025-09-17T23:40:46.069+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:46.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:40:46.073+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:40:46.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:46.593+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:40:46.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:40:46.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:40:46.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.578 seconds
[2025-09-17T23:41:17.620+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:17.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:41:17.625+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:41:17.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:18.244+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:41:18.234+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:41:18.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:18.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.677 seconds
[2025-09-17T23:41:48.787+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:48.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:41:48.792+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:41:48.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:49.327+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:41:49.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:41:49.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:41:49.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.610 seconds
[2025-09-17T23:42:20.063+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:20.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:42:20.070+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:42:20.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:20.609+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:42:20.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:42:20.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:20.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.607 seconds
[2025-09-17T23:42:51.401+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:51.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:42:51.415+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:42:51.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:52.058+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:42:52.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:42:52.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:42:52.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.764 seconds
[2025-09-17T23:43:22.694+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:43:22.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:43:22.706+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:43:22.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:43:23.242+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:43:23.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:43:23.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:43:23.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.621 seconds
[2025-09-17T23:43:58.785+0000] {processor.py:161} INFO - Started process (PID=25) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:43:58.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:43:58.790+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:43:58.790+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:44:00.400+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:44:00.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:44:00.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:44:00.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 1.660 seconds
[2025-09-17T23:44:31.154+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:44:31.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:44:31.161+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:44:31.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:44:31.699+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:44:31.683+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:44:31.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:44:31.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.606 seconds
[2025-09-17T23:45:02.473+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:02.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:45:02.480+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:45:02.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:03.054+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:45:03.025+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:45:03.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:03.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.672 seconds
[2025-09-17T23:45:33.809+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:33.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:45:33.817+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:45:33.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:34.427+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:45:34.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:45:34.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:45:34.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.698 seconds
[2025-09-17T23:46:05.126+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:05.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:46:05.131+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:46:05.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:05.623+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:46:05.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:46:05.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:05.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.573 seconds
[2025-09-17T23:46:35.881+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:35.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:46:35.886+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:46:35.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:36.471+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:46:36.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:46:36.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:46:36.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.654 seconds
[2025-09-17T23:47:07.217+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:47:07.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:47:07.223+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:47:07.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:47:07.756+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:47:07.748+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:47:07.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:47:07.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.584 seconds
[2025-09-17T23:48:03.835+0000] {processor.py:161} INFO - Started process (PID=24) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:03.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:48:03.839+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:48:03.838+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:04.337+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:48:04.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:48:04.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:04.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.559 seconds
[2025-09-17T23:48:35.434+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:35.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:48:35.452+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:48:35.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:36.092+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:48:36.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:48:36.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:48:36.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.745 seconds
[2025-09-17T23:49:06.708+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:06.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:49:06.716+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:49:06.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:07.207+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:49:07.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:49:07.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:07.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.590 seconds
[2025-09-17T23:49:37.473+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:37.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:49:37.479+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:49:37.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:38.008+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:49:37.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:49:38.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:49:38.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.595 seconds
[2025-09-17T23:50:08.683+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:08.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:50:08.723+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:50:08.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:09.261+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:50:09.241+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:50:09.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:09.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.658 seconds
[2025-09-17T23:50:39.486+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:39.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/clean_users_dag.py for tasks to queue
[2025-09-17T23:50:39.492+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:50:39.491+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:40.028+0000] {logging_mixin.py:188} INFO - [2025-09-17T23:50:40.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/clean_users_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/clean_users_dag.py", line 6, in <module>
    from src.Lake.lake_connection import get_minio_client
  File "/opt/airflow/src/Lake/lake_connection.py", line 3, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-09-17T23:50:40.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/clean_users_dag.py
[2025-09-17T23:50:40.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/clean_users_dag.py took 0.609 seconds
